### ISSUE TITLE
debops.mysql installation faild with 'ansible_local' is undefined"

### ISSUE THREAD

**Issue by Zeboton** [debops/ansible-mysql#12]
Hi!

I'm trying install debops.mysql in local vm ( created manual without vagrant ) and get an error:

```
 TASK [debops.secret : Create secret directories on Ansible Controller] *********
task path: /home/developer/ansible.server/roles/debops.secret/tasks/main.yml:3

TASK [debops.ferm : Configure ferm status in debconf] **************************
task path: /home/developer/ansible.server/roles/debops.ferm/tasks/main.yml:3
fatal: [ansible]: FAILED! => {"failed": true, "msg": "'ansible_local' is undefined"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @06. mysql.retry

PLAY RECAP *********************************************************************
ansible                    : ok=1    changed=0    unreachable=0    failed=1 
```

**Comment by drybjed** [comment]
This means that there are no local Ansible facts present. Most of the roles try to handle that, looks like `debops.mysql` hasn't been updated.

To fix the problem, add the `debops.core` role to your playbook. It will configure some of the local Ansible facts which other roles expect and this error shouldn't occur anymore.

You should also look into switching to `debops.mariadb` and `debops.mariadb_server` roles instead, this role will be deprecated at some point.

**Comment by Zeboton** [comment]
Thanks for flash answer!

debops.core has solved the problem.

As you suggest I will try debops.mariadb_server instead debops.mysql.

DebOps is a great project! It's very helpful for me. Thank you!

**Comment by drybjed** [comment]
Glad you like it. The `debops.mariadb` is a client-side counterpart, so you might need to use that as well. Check [the documentation](http://docs.debops.org/en/latest/ansible/roles/ansible-mariadb/docs/getting-started.html) for more details. :-)
